export const REQUIRED_DATABASE_FUNCTIONS = [
  "fn_admin_master_registrar_auditoria",
  "fn_aplicar_estoque_comanda",
  "fn_avaliar_trial_extra",
  "fn_cadastrar_salao_transacional",
  "fn_caixa_abrir_sessao",
  "fn_caixa_adicionar_pagamento",
  "fn_caixa_adicionar_pagamento_v2",
  "fn_caixa_cancelar_comanda",
  "fn_caixa_fechar_sessao",
  "fn_caixa_finalizar_comanda",
  "fn_caixa_lancar_movimentacao",
  "fn_caixa_lancar_movimentacao_v2",
  "fn_caixa_remover_pagamento",
  "fn_comanda_adicionar_item",
  "fn_comanda_adicionar_item_v2",
  "fn_comanda_atualizar_item",
  "fn_criar_comanda_por_agendamento",
  "fn_detalhes_venda",
  "fn_excluir_produto_catalogo",
  "fn_excluir_servico_catalogo",
  "fn_excluir_venda_completa",
  "fn_get_or_create_servico_categoria",
  "fn_processar_renovacao_assinatura",
  "fn_reabrir_venda_para_caixa",
  "fn_remover_item_comanda",
  "fn_reverter_estoque_comanda",
  "fn_salvar_comanda_base",
  "fn_salvar_servico_catalogo_transacional",
] as const;

export type RequiredDatabaseFunction = (typeof REQUIRED_DATABASE_FUNCTIONS)[number];
