export type AutomationRisk = "SAFE_AUTO" | "APPROVAL_REQUIRED" | "FORBIDDEN_AUTO";
export type OperationalConfidence = "baixa" | "media" | "alta";

export type ErrorCatalogRule = {
  code: string;
  name: string;
  category: string;
  severity: "baixa" | "media" | "alta" | "critica";
  symptom: string;
  probableCauses: string[];
  evidenceNeeded: string[];
  componentKey?: string;
  owner: string;
  recommendedAction: string;
  automaticFixAvailable: boolean;
  automationRisk: AutomationRisk;
  runbook: string;
  recoveryCondition: string;
  confidence: OperationalConfidence;
  opensIncident: boolean;
  publicSafe: boolean;
  match: (input: ErrorCatalogInput) => boolean;
};

export type ErrorCatalogInput = {
  message?: string | null;
  errorCode?: string | null;
  module?: string | null;
  route?: string | null;
  action?: string | null;
  origin?: string | null;
};

function text(input: ErrorCatalogInput) {
  return [input.errorCode, input.message, input.module, input.route, input.action, input.origin]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
}

const runbook = "/docs/operational-health#catalogo-de-erros";

export const ERROR_CATALOG: ErrorCatalogRule[] = [
  {
    code: "react_hydration_mismatch",
    name: "React hydration mismatch",
    category: "frontend_render",
    severity: "alta",
    symptom: "A tela pode renderizar conteúdo diferente no servidor e navegador e refazer a árvore no cliente.",
    probableCauses: [
      "Data, hora, locale ou timezone diferentes entre SSR e navegador.",
      "Conteúdo condicionado a APIs do navegador no primeiro render.",
      "Valor aleatório, relógio atual ou HTML inválido durante a hidratação."
    ],
    evidenceNeeded: ["Código React #418 ou mensagem de hydration.", "Rota afetada.", "Comparação do HTML SSR com o primeiro render do cliente."],
    componentKey: "client.appointments",
    owner: "App Cliente",
    recommendedAction: "Comparar SSR e primeiro render e tornar datas, locale e conteúdo inicial determinísticos; não mascarar com suppressHydrationWarning.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Probe da superfície saudável, sem nova ocorrência na janela e verificações consecutivas saudáveis.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /react_hydration_mismatch|minified react error #418|hydration (failed|mismatch)|text content does not match/i.test(text(input))
  },
  {
    code: "chunk_load_failed",
    name: "Falha real de chunk",
    category: "frontend_asset",
    severity: "alta",
    symptom: "O navegador não conseguiu carregar um chunk JavaScript necessário.",
    probableCauses: ["Cache ou service worker com versão antiga.", "Asset removido após deployment.", "Falha de rede/CDN durante import dinâmico."],
    evidenceNeeded: ["ChunkLoadError ou import dinâmico falhou.", "URL do asset sem query sensível.", "Deployment atual."],
    componentKey: "platform.assets",
    owner: "Frontend/Plataforma",
    recommendedAction: "Validar versão do asset e service worker; a recuperação segura pode revalidar cache e recarregar uma vez.",
    automaticFixAvailable: true,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Asset atual carrega e o erro não reaparece após probes consecutivos.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /chunk_load_failed|chunkloaderror|loading chunk .* failed|failed to load chunk|dynamically imported module/i.test(text(input))
  },
  {
    code: "stale_service_worker",
    name: "Service worker desatualizado",
    category: "frontend_asset",
    severity: "media",
    symptom: "O PWA está usando cache incompatível com a versão publicada.",
    probableCauses: ["Service worker antigo ainda controlando a aba.", "Cache Storage com assets de deployment anterior."],
    evidenceNeeded: ["Versão/cache do service worker.", "Asset solicitado e deployment atual."],
    componentKey: "client.pwa",
    owner: "PWA/Frontend",
    recommendedAction: "Atualizar service worker e revalidar apenas caches relacionados ao app.",
    automaticFixAvailable: true,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Service worker atualizado e assets atuais carregando.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /stale_service_worker|stale service worker|service worker.*outdated/i.test(text(input))
  },
  {
    code: "asset_version_mismatch",
    name: "Versão de asset incompatível",
    category: "frontend_asset",
    severity: "alta",
    symptom: "HTML e assets apontam para versões incompatíveis do deployment.",
    probableCauses: ["Deployment trocado enquanto uma aba antiga estava aberta.", "Cache intermediário desatualizado."],
    evidenceNeeded: ["Build/deployment IDs.", "Asset solicitado.", "Timestamp do deployment."],
    componentKey: "platform.assets",
    owner: "Infra/Frontend",
    recommendedAction: "Confirmar deployment atual e invalidar/revalidar apenas caches seguros.",
    automaticFixAvailable: true,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "HTML e assets atuais pertencem ao mesmo deployment.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /asset_version_mismatch|build.?id mismatch|deployment version mismatch/i.test(text(input))
  },
  {
    code: "missing_neon_connection",
    name: "Conexão Neon ausente",
    category: "configuration",
    severity: "critica",
    symptom: "Operações server-side que exigem cliente administrativo do Neon não podem executar.",
    probableCauses: ["NEON_DATABASE_URL e NEON_ADMIN_DATABASE_URL não configuradas."],
    evidenceNeeded: ["Deployment afetado.", "Configuração presente true/false, sem registrar o valor."],
    componentKey: "database.data_api",
    owner: "Infra/Backend",
    recommendedAction: "Configurar a variável secreta no ambiente correto e publicar um novo deployment; nunca enviar a chave ao cliente.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Deployment atual possui configuração e probes server-side passam consecutivamente.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: false,
    match: (input) => /neon_(admin_)?database_url.*(nao|não) configurada/i.test(text(input))
  },
  {
    code: "missing_neon_config",
    name: "URL Neon ausente",
    category: "configuration",
    severity: "critica",
    symptom: "O cliente Neon server-side não pode ser inicializado.",
    probableCauses: ["NEON_DATABASE_URL ausente no ambiente."],
    evidenceNeeded: ["Deployment afetado.", "Flags configurado true/false."],
    componentKey: "database.data_api",
    owner: "Infra/Backend",
    recommendedAction: "Configurar a URL Neon somente no servidor e validar novamente.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Configuração presente no deployment atual e Data API saudável.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: false,
    match: (input) => /project'?s url and key are required|database.*url.*key.*required/i.test(text(input))
  },
  {
    code: "missing_professional_session_secret",
    name: "Secret de sessão profissional ausente",
    category: "configuration",
    severity: "critica",
    symptom: "O App Profissional não consegue criar ou validar sessão assinada.",
    probableCauses: ["PROFISSIONAL_SESSION_SECRET ausente no deployment."],
    evidenceNeeded: ["Deployment afetado.", "Flag configurado true/false."],
    componentKey: "professional.auth",
    owner: "App Profissional/Auth",
    recommendedAction: "Configurar o secret no ambiente server-side e validar login no deployment atual.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Secret configurado e probe de autenticação profissional saudável.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: false,
    match: (input) => /profissional_session_secret.*nao configurada|profissional_session_secret.*não configurada/i.test(text(input))
  },
  {
    code: "invalid_user_credentials",
    name: "Credenciais inválidas do usuário",
    category: "user_behavior",
    severity: "baixa",
    symptom: "Uma tentativa de login foi recusada por credenciais inválidas.",
    probableCauses: ["CPF, e-mail ou senha digitados incorretamente."],
    evidenceNeeded: ["Resposta de autenticação sem erro interno."],
    owner: "Segurança/Auth",
    recommendedAction: "Registrar como evento de segurança/analytics; não tratar uma tentativa normal como outage.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Não se aplica a incidente operacional isolado.",
    confidence: "alta",
    opensIncident: false,
    publicSafe: false,
    match: (input) => /invalid login credentials|cpf ou senha invalidos|cpf ou senha inválidos|senha incorreta|credenciais invalidas|credenciais inválidas/i.test(text(input))
  },
  {
    code: "session_expired",
    name: "Sessão expirada",
    category: "user_behavior",
    severity: "baixa",
    symptom: "A sessão do usuário expirou ou não é mais válida.",
    probableCauses: ["Expiração natural da sessão.", "Sessão revogada por segurança."],
    evidenceNeeded: ["Código 401/redirect esperado sem falha de backend."],
    owner: "Segurança/Auth",
    recommendedAction: "Solicitar novo login e acompanhar apenas anomalias agregadas.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Não se aplica a outage isolado.",
    confidence: "media",
    opensIncident: false,
    publicSafe: false,
    match: (input) => /sess[aã]o expirada|sess[aã]o invalida|sess[aã]o inválida|unauthorized.*session/i.test(text(input))
  },
  {
    code: "rls_permission_denied",
    name: "RLS/permissão negada",
    category: "database_security",
    severity: "alta",
    symptom: "Uma operação válida foi recusada pelo banco por política ou privilégio.",
    probableCauses: ["Policy RLS incompatível com o fluxo.", "Grant ausente.", "Contexto de usuário/salão incorreto."],
    evidenceNeeded: ["Código Postgres sanitizado.", "Tabela e operação sem dados pessoais.", "Policy aplicável."],
    componentKey: "database.database",
    owner: "Backend/Segurança",
    recommendedAction: "Revisar grant e policy sem desabilitar RLS nem ampliar acesso de forma genérica.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Operação canário autorizada passa e políticas permanecem restritivas.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: false,
    match: (input) => /42501|row-level security|permission denied|rls/i.test(text(input))
  },
  {
    code: "security_definer_risk",
    name: "Risco SECURITY DEFINER",
    category: "security_recommendation",
    severity: "media",
    symptom: "Função privilegiada pode ampliar acesso se exposta ou sem validação adequada.",
    probableCauses: ["SECURITY DEFINER em schema exposto.", "EXECUTE concedido a roles públicas."],
    evidenceNeeded: ["Definição da função.", "ACL/EXECUTE.", "search_path."],
    componentKey: "database.database",
    owner: "Backend/Segurança",
    recommendedAction: "Revisar necessidade, search_path, autenticação interna e privilégios; não alterar automaticamente apenas por Advisor.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Revisão concluída e acesso comprovadamente mínimo.",
    confidence: "media",
    opensIncident: false,
    publicSafe: false,
    match: (input) => /security definer|security_definer/i.test(text(input))
  },
  {
    code: "database_unavailable",
    name: "Banco indisponível",
    category: "database",
    severity: "critica",
    symptom: "Operações essenciais não conseguem acessar o PostgreSQL.",
    probableCauses: ["Banco indisponível.", "Pool/conexão esgotada.", "Falha de rede entre runtime e banco."],
    evidenceNeeded: ["Probe de banco.", "Erros recentes de conexão.", "Latência."],
    componentKey: "database.database",
    owner: "Backend/Dados",
    recommendedAction: "Confirmar saúde do projeto, conexões e logs do banco antes de alterar schema ou limites.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Três probes consecutivos de leitura saudável e dependências sem falha contraditória.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /connection refused|connection closed|database.*unavailable|remaining connection slots|too many connections/i.test(text(input))
  },
  {
    code: "database_slow",
    name: "Banco lento",
    category: "performance",
    severity: "media",
    symptom: "Consultas essenciais apresentam latência acima do SLO.",
    probableCauses: ["Query sem índice adequado.", "Contenção ou carga elevada.", "Dependência externa lenta."],
    evidenceNeeded: ["p95/p99.", "Query/rota agregada.", "Advisor como recomendação, não causa automática."],
    componentKey: "database.database",
    owner: "Backend/Dados",
    recommendedAction: "Medir consultas reais e justificar otimização antes de criar ou remover índices.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Latência volta abaixo do limite por janela suficiente.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /database_slow|slow query|statement timeout|query timeout/i.test(text(input))
  },
  {
    code: "request_timeout",
    name: "Timeout",
    category: "network",
    severity: "alta",
    symptom: "Uma operação excedeu o tempo limite esperado.",
    probableCauses: ["Dependência lenta.", "Rede instável.", "Consulta ou processamento excedendo SLO."],
    evidenceNeeded: ["Componente/rota.", "response_ms.", "Dependência chamada."],
    owner: "Backend/Integrações",
    recommendedAction: "Identificar a dependência e comparar latência com p95 antes de aumentar timeout.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Taxa de timeout abaixo do limite e probes saudáveis.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /timeout|timed out|etimedout|aborterror/i.test(text(input))
  },
  {
    code: "network_fetch_failed",
    name: "Falha de rede/fetch",
    category: "network",
    severity: "alta",
    symptom: "A aplicação não conseguiu alcançar uma API ou dependência.",
    probableCauses: ["Rede do cliente/runtime.", "Dependência fora do ar.", "CORS/DNS/SSL."],
    evidenceNeeded: ["Origem e rota.", "Status HTTP quando disponível.", "Probe da dependência."],
    owner: "Plataforma/Integrações",
    recommendedAction: "Correlacionar com o probe da dependência antes de concluir a causa raiz.",
    automaticFixAvailable: false,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Dependência e rota passam em probes consecutivos.",
    confidence: "baixa",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /failed to fetch|network request failed|networkerror|err_network/i.test(text(input))
  },
  {
    code: "api_5xx",
    name: "API 5xx",
    category: "api",
    severity: "alta",
    symptom: "Uma API respondeu com erro interno.",
    probableCauses: ["Exceção server-side.", "Dependência indisponível.", "Configuração ausente."],
    evidenceNeeded: ["Rota normalizada.", "Status HTTP.", "Erro interno sanitizado."],
    componentKey: "platform.api",
    owner: "Backend/Plataforma",
    recommendedAction: "Classificar a exceção original e verificar dependências da rota.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Taxa 5xx abaixo do limite e probe da rota saudável.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /api_5xx|http 5\d\d|status 5\d\d/i.test(text(input))
  },
  {
    code: "api_slow",
    name: "API lenta",
    category: "performance",
    severity: "media",
    symptom: "Uma rota excedeu o limite de latência operacional.",
    probableCauses: ["Banco/dependência lenta.", "Processamento excessivo."],
    evidenceNeeded: ["p50/p95/p99 e volume.", "Rota normalizada."],
    componentKey: "platform.api",
    owner: "Backend/Plataforma",
    recommendedAction: "Localizar o estágio lento com métricas antes de otimizar.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "p95 retorna ao SLO por janela suficiente.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /api_slow|slow route|rota lenta/i.test(text(input))
  },
  {
    code: "webhook_failed",
    name: "Webhook com falha",
    category: "webhook",
    severity: "alta",
    symptom: "Um webhook não foi processado com sucesso.",
    probableCauses: ["Payload inválido.", "Dependência/banco indisponível.", "Regra de negócio inesperada."],
    evidenceNeeded: ["Evento e status sanitizados.", "Tentativas.", "Erro sem payload sensível."],
    componentKey: "integration.asaas.webhooks",
    owner: "Pagamentos/Webhooks",
    recommendedAction: "Diagnosticar o erro e reprocessar somente se a operação for idempotente.",
    automaticFixAvailable: true,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Backlog zerado ou abaixo do limite e processamentos recentes saudáveis.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /webhook.*(erro|falha|failed)|webhook_failed/i.test(text(input))
  },
  {
    code: "webhook_stale",
    name: "Webhook atrasado",
    category: "webhook",
    severity: "media",
    symptom: "A última entrega esperada está atrasada ou existe backlog anormal.",
    probableCauses: ["Origem parou de entregar.", "Processador atrasado."],
    evidenceNeeded: ["Última entrega.", "Backlog.", "Intervalo histórico esperado."],
    componentKey: "integration.asaas.webhooks",
    owner: "Pagamentos/Webhooks",
    recommendedAction: "Comparar freshness com o volume real e verificar backlog antes de declarar outage.",
    automaticFixAvailable: false,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Freshness normalizada e backlog dentro do limite.",
    confidence: "baixa",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /webhook_stale|webhook atrasado|webhook delayed/i.test(text(input))
  },
  {
    code: "asaas_error",
    name: "Falha Asaas",
    category: "payment",
    severity: "alta",
    symptom: "Cobrança, assinatura ou consulta ao Asaas falhou.",
    probableCauses: ["Rejeição da API.", "Credencial/configuração.", "Timeout ou indisponibilidade externa."],
    evidenceNeeded: ["Operação Asaas.", "Código/status sanitizado.", "Probe/telemetria recente."],
    componentKey: "integration.asaas.api",
    owner: "Pagamentos/Asaas",
    recommendedAction: "Distinguir rejeição de negócio, timeout e indisponibilidade antes de tentar novamente.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Operações de leitura/fluxos idempotentes saudáveis e taxa de erro normal.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /asaas.*(erro|falha|failed|timeout|recus)|asaas_error/i.test(text(input))
  },
  {
    code: "push_subscription_invalid",
    name: "Subscription push inválida",
    category: "push",
    severity: "baixa",
    symptom: "Um endpoint Web Push expirou ou foi invalidado pelo navegador.",
    probableCauses: ["Subscription expirada ou revogada."],
    evidenceNeeded: ["Status 404/410 do serviço push sem armazenar endpoint público."],
    componentKey: "communication.push_vapid",
    owner: "Comunicação/Push",
    recommendedAction: "Invalidar somente a subscription afetada e solicitar nova inscrição quando o usuário retornar.",
    automaticFixAvailable: true,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Subscription inválida removida; não é outage global isoladamente.",
    confidence: "alta",
    opensIncident: false,
    publicSafe: false,
    match: (input) => /push.*(404|410|subscription.*invalid|expired subscription)/i.test(text(input))
  },
  {
    code: "push_vapid_config",
    name: "Configuração VAPID ausente",
    category: "configuration",
    severity: "alta",
    symptom: "Notificações Web Push não podem ser assinadas ou enviadas.",
    probableCauses: ["VAPID public/private key ausente ou incompatível."],
    evidenceNeeded: ["Flags de configuração true/false."],
    componentKey: "communication.push_vapid",
    owner: "Comunicação/Push",
    recommendedAction: "Restaurar o par VAPID no ambiente correto sem registrar o valor das chaves.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Configuração presente e entrega canário/telemetria saudável.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: false,
    match: (input) => /vapid.*(nao configur|não configur|missing|invalid)/i.test(text(input))
  },
  {
    code: "whatsapp_error",
    name: "Falha WhatsApp",
    category: "communication",
    severity: "media",
    symptom: "Envio ou integração WhatsApp falhou.",
    probableCauses: ["Token/configuração.", "API externa indisponível.", "Sessão/provedor inválido quando aplicável."],
    evidenceNeeded: ["Provedor detectado.", "Status sanitizado.", "Configuração true/false."],
    componentKey: "communication.whatsapp",
    owner: "Comunicação/WhatsApp",
    recommendedAction: "Diagnosticar o provedor realmente configurado; não presumir WAHA quando o código usa Meta API.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Configuração/provedor saudável e taxa de erro normal.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /whatsapp.*(erro|falha|failed|timeout)|waha.*(erro|falha|failed)/i.test(text(input))
  },
  {
    code: "cron_stale",
    name: "Cron atrasado",
    category: "automation",
    severity: "alta",
    symptom: "Uma rotina agendada não executou dentro do intervalo esperado e tolerância.",
    probableCauses: ["Cron não disparou.", "Rota rejeitou autenticação.", "Execução anterior travou/falhou."],
    evidenceNeeded: ["Última execução.", "Schedule esperado.", "Último status."],
    componentKey: "automation.cron",
    owner: "Automação/Backend",
    recommendedAction: "Comparar última execução com o schedule e investigar a rota antes de disparar manualmente.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Execução atual concluída com sucesso e freshness normalizada.",
    confidence: "alta",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /cron_stale|cron atrasado|job atrasado|job stale/i.test(text(input))
  },
  {
    code: "storage_error",
    name: "Falha de Storage",
    category: "storage",
    severity: "alta",
    symptom: "Operação de armazenamento falhou.",
    probableCauses: ["Storage indisponível.", "Policy/permissão.", "Bucket/configuração ausente."],
    evidenceNeeded: ["Probe read-only/listagem segura.", "Código sanitizado."],
    componentKey: "cloudinary.storage",
    owner: "Backend/Midia",
    recommendedAction: "Verificar credenciais, tipo de recurso e resposta da API Cloudinary.",
    automaticFixAvailable: false,
    automationRisk: "FORBIDDEN_AUTO",
    runbook,
    recoveryCondition: "Probe seguro de Storage passa consecutivamente.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /storage.*(erro|falha|failed|bucket)/i.test(text(input))
  },
  {
    code: "periodic_sync_error",
    name: "Falha de atualização periódica",
    category: "synchronization",
    severity: "media",
    symptom: "Agenda ou caixa não conseguem executar a atualização periódica.",
    probableCauses: ["Gateway Neon indisponível.", "Sessão Clerk expirada.", "Rede do cliente."],
    evidenceNeeded: ["Resposta do gateway.", "Erros agregados de atualização."],
    componentKey: "database.periodic_sync",
    owner: "Backend/Sincronizacao",
    recommendedAction: "Verificar sessão, gateway e conectividade antes de declarar indisponibilidade.",
    automaticFixAvailable: true,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Atualizações periódicas voltam a concluir sem erro.",
    confidence: "baixa",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /periodic.?sync.*(erro|failed|timeout)|atualizacao periodica.*(erro|falha)/i.test(text(input))
  },
  {
    code: "edge_function_error",
    name: "Falha de Edge Function",
    category: "edge_function",
    severity: "alta",
    symptom: "Uma Edge Function implantada falhou ou não respondeu.",
    probableCauses: ["Erro de função.", "Secret/configuração.", "Função removida ou não implantada."],
    evidenceNeeded: ["Função realmente detectada no projeto.", "Logs recentes."],
    owner: "Backend/Edge",
    recommendedAction: "Confirmar que a função existe no projeto antes de diagnosticar; não criar componente fictício.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Função detectada e probe/logs atuais saudáveis.",
    confidence: "baixa",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /edge function.*(erro|failed|timeout)|edge_function_error/i.test(text(input))
  },
  {
    code: "dependency_degraded",
    name: "Dependência degradada",
    category: "dependency",
    severity: "media",
    symptom: "Um componente depende de outro que está degradado ou indisponível.",
    probableCauses: ["Falha na dependência raiz."],
    evidenceNeeded: ["Grafo de dependências.", "Probe da causa raiz."],
    owner: "Plataforma",
    recommendedAction: "Tratar a causa raiz e correlacionar sintomas dependentes em vez de abrir incidentes independentes.",
    automaticFixAvailable: true,
    automationRisk: "SAFE_AUTO",
    runbook,
    recoveryCondition: "Dependência raiz recuperada e componentes derivados verificados.",
    confidence: "media",
    opensIncident: true,
    publicSafe: true,
    match: (input) => /dependency_degraded|dependencia degradada|dependência degradada/i.test(text(input))
  },
  {
    code: "unknown_operational_error",
    name: "Erro operacional desconhecido",
    category: "unknown",
    severity: "alta",
    symptom: "O sistema registrou uma falha que ainda não possui regra específica no catálogo.",
    probableCauses: ["Causa ainda não classificada."],
    evidenceNeeded: ["Mensagem sanitizada.", "Componente/rota.", "Stack frame relevante sem PII.", "Deployment."],
    owner: "Observabilidade",
    recommendedAction: "Investigar o contexto, identificar a causa e adicionar uma regra ao catálogo se o padrão for recorrente.",
    automaticFixAvailable: false,
    automationRisk: "APPROVAL_REQUIRED",
    runbook,
    recoveryCondition: "Probe do componente saudável e ausência de evidência contraditória; causa continua registrada como desconhecida até revisão.",
    confidence: "baixa",
    opensIncident: true,
    publicSafe: false,
    match: () => true
  }
];

export function classifyOperationalError(input: ErrorCatalogInput) {
  return ERROR_CATALOG.find((rule) => rule.match(input)) || ERROR_CATALOG[ERROR_CATALOG.length - 1];
}
