import { unstable_cache, unstable_noStore as noStore } from "next/cache";
import type { BlogCategory, BlogPost } from "@/lib/blog/content";
import { canUseBlogDatabase, getBlogDatabase } from "@/lib/blog/database";
import { asLooseDbClient, type LooseDbClient } from "@/lib/db/loose-client";

type BlogDbCategory={id:string;slug:string;nome:string;descricao:string|null};
type BlogDbPost={id:string;categoria_id?:string;slug:string;titulo:string;descricao:string;resumo:string|null;conteudo:string;imagem_capa_url:string|null;imagem_capa_alt:string|null;tempo_leitura:string|null;tags:string[]|null;status?:"rascunho"|"publicado"|"arquivado";destaque:boolean|null;views?:number|null;publicado_em:string|null;categoria:BlogDbCategory|null};
export type BlogAdminMetrics={totalViews:number;newsletterSubscribers:number;conversionRate:number;topPostWeek:{title:string;slug:string;views:number}|null;viewsLast7Days:{date:string;label:string;views:number}[]};
function createEmptyMetrics():BlogAdminMetrics{const f=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit"});const today=new Date();return{totalViews:0,newsletterSubscribers:0,conversionRate:0,topPostWeek:null,viewsLast7Days:Array.from({length:7},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-(6-i));const date=d.toISOString().slice(0,10);return{date,label:f.format(d),views:0}})}}
function splitBody(v:string){return v.split(/\n{2,}/).map(p=>p.trim()).filter(Boolean)}
function looksLikeHtml(v:string){return /<\/?[a-z][\s\S]*>/i.test(v)}
function looksLikeUuid(v?:string|null){return Boolean(String(v||"").match(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i))}
function readableCategoryName(c:BlogDbCategory){return looksLikeUuid(c.slug)||looksLikeUuid(c.nome.replace(/\s+/g,"-"))?"Agenda online":c.nome}
function mapCategory(c:BlogDbCategory):BlogCategory{return{id:c.id,slug:looksLikeUuid(c.slug)?"agenda-online":c.slug,name:readableCategoryName(c),description:c.descricao||"Artigos do blog SalãoPremium."}}
function mapPost(p:BlogDbPost):BlogPost{const c=p.categoria;return{id:p.id,slug:p.slug,title:p.titulo,description:p.descricao,excerpt:p.resumo||p.descricao,categorySlug:c?(looksLikeUuid(c.slug)?"agenda-online":c.slug):"gestao",categoryName:c?readableCategoryName(c):"Gestão",readTime:p.tempo_leitura||"5 min",publishedAt:p.publicado_em||new Date().toISOString(),coverImage:p.imagem_capa_url||"/marketing-kit/site-hero.png",coverAlt:p.imagem_capa_alt||p.titulo,tags:p.tags||[],body:splitBody(p.conteudo),bodyHtml:looksLikeHtml(p.conteudo)?p.conteudo:splitBody(p.conteudo).map(x=>`<p>${x}</p>`).join(""),featured:Boolean(p.destaque),views:Number(p.views||0),categoryId:p.categoria_id||c?.id,status:p.status||"publicado",rawContent:p.conteudo}}
function isSeoBlockedBlogPost(p:BlogDbPost){const s=String(p.slug||"").toLowerCase();const t=String(p.titulo||"").toLowerCase();return s.startsWith("post-teste-automatico")||s.startsWith("teste-automatico")||t.includes("post teste automático")||t.includes("post teste automatico")}
async function db():Promise<LooseDbClient|null>{if(!canUseBlogDatabase())return null;return asLooseDbClient(getBlogDatabase())}
async function loadBlogCategories():Promise<BlogCategory[]>{try{const client=await db();if(!client)return[];const{data,error}=await client.from<BlogDbCategory[]>("blog_categorias").select("id, slug, nome, descricao").eq("ativo",true).order("ordem",{ascending:true}).order("nome",{ascending:true});if(error||!data?.length)return[];return(data as BlogDbCategory[]).map(mapCategory)}catch(error){console.warn("Blog sem categorias carregadas:",error);return[]}}
const categoriesCached=unstable_cache(loadBlogCategories,["blog-categories-v3"],{revalidate:600,tags:["blog-public"]});
export async function getBlogCategories(){return categoriesCached()}
async function loadPublishedBlogPosts():Promise<BlogPost[]>{try{const client=await db();if(!client)return[];const{data,error}=await client.from<BlogDbPost[]>("blog_posts").select("id, categoria_id, slug, titulo, descricao, resumo, conteudo, imagem_capa_url, imagem_capa_alt, tempo_leitura, tags, destaque, views, publicado_em, categoria:blog_categorias(id, slug, nome, descricao)").eq("status","publicado").order("publicado_em",{ascending:false,nullsFirst:false}).order("criado_em",{ascending:false});if(error||!data?.length)return[];return(data as BlogDbPost[]).filter(p=>!isSeoBlockedBlogPost(p)).map(mapPost)}catch(error){console.warn("Blog sem posts carregados:",error);return[]}}
const postsCached=unstable_cache(loadPublishedBlogPosts,["blog-posts-publicados-v3"],{revalidate:300,tags:["blog-public"]});
export async function getPublishedBlogPosts(){return postsCached()}
export async function getBlogPost(slug:string){return(await getPublishedBlogPosts()).find(p=>p.slug===slug)||null}
export async function getBlogAdminMetrics():Promise<BlogAdminMetrics>{noStore();const m=createEmptyMetrics();try{const client=await db();if(!client)return m;const[{data:posts},{count:subs}]=await Promise.all([client.from("blog_posts").select("id, slug, titulo, views"),client.from("newsletter_subscribers").select("id",{count:"exact",head:true})]);const list=(posts||[]) as Array<{id:string;slug:string;titulo:string;views:number|null}>;m.totalViews=list.reduce((a,p)=>a+Number(p.views||0),0);m.newsletterSubscribers=Number(subs||0);m.conversionRate=m.totalViews?Number(((m.newsletterSubscribers/m.totalViews)*100).toFixed(1)):0;const first=m.viewsLast7Days[0]?.date;if(!first)return m;const{data:views}=await client.from("blog_views").select("post_id, criado_em").gte("criado_em",`${first}T00:00:00.000Z`);const postMap=new Map(list.map(p=>[p.id,p]));const byDay=new Map(m.viewsLast7Days.map(d=>[d.date,d]));const byPost=new Map<string,number>();for(const v of(views||[]) as Array<{post_id:string|null;criado_em:string|null}>){if(!v.criado_em)continue;const day=byDay.get(v.criado_em.slice(0,10));if(day)day.views+=1;if(v.post_id)byPost.set(v.post_id,(byPost.get(v.post_id)||0)+1)}const top=Array.from(byPost.entries()).sort((a,b)=>b[1]-a[1])[0];if(top){const p=postMap.get(top[0]);if(p)m.topPostWeek={title:p.titulo,slug:p.slug,views:top[1]}}return m}catch(error){console.warn("Métricas do blog indisponíveis:",error);return m}}
export async function getAdminBlogData(){noStore();const metrics=await getBlogAdminMetrics();try{const client=await db();if(!client)return{categories:[],posts:[],metrics,usingFallback:true,error:"A conexão Neon do blog não está configurada neste ambiente."};const[{data:cats,error:catError},{data:posts,error}]=await Promise.all([client.from<BlogDbCategory[]>("blog_categorias").select("id, slug, nome, descricao").eq("ativo",true).order("ordem",{ascending:true}).order("nome",{ascending:true}),client.from("blog_posts").select("id, categoria_id, slug, titulo, descricao, resumo, conteudo, imagem_capa_url, imagem_capa_alt, tempo_leitura, tags, destaque, views, publicado_em, status, categoria:blog_categorias(id, slug, nome, descricao)").order("atualizado_em",{ascending:false}).limit(100)]);const categories=catError?[]:((cats||[]) as BlogDbCategory[]).map(mapCategory);if(error)return{categories,posts:[],metrics,usingFallback:true,error:error.message};return{categories,posts:((posts||[]) as BlogDbPost[]).map(mapPost),metrics,usingFallback:false,error:null}}catch(error){return{categories:[],posts:[],metrics,usingFallback:true,error:error instanceof Error?error.message:"Não foi possível ler os posts na base Neon."}}}
async function adminPost(field:"id"|"slug",value:string):Promise<BlogPost|null>{noStore();try{const client=await db();if(!client)return null;const{data,error}=await client.from("blog_posts").select("id, categoria_id, slug, titulo, descricao, resumo, conteudo, imagem_capa_url, imagem_capa_alt, tempo_leitura, tags, destaque, views, publicado_em, status, categoria:blog_categorias(id, slug, nome, descricao)").eq(field,value).maybeSingle();return error||!data?null:mapPost(data as BlogDbPost)}catch{return null}}
export async function getAdminBlogPostById(id:string){return adminPost("id",id)}
export async function getAdminBlogPostBySlug(slug:string){return adminPost("slug",slug)}
export async function getAdminBlogPostBySlugOrId(value:string){return(await getAdminBlogPostBySlug(value))||getAdminBlogPostById(value)}
