import { unstable_cache, unstable_noStore as noStore } from "next/cache";
import type { BlogCategory, BlogPost } from "@/lib/blog/content";
import { canUseBlogDatabase, getBlogDatabase } from "@/lib/blog/database";
import { asLooseDbClient, type LooseDbClient } from "@/lib/db/loose-client";

type BlogDbCategory = { id:string; slug:string; nome:string; descricao:string|null };
type BlogDbPost = { id:string; categoria_id?:string; slug:string; titulo:string; descricao:string; resumo:string|null; conteudo:string; imagem_capa_url:string|null; imagem_capa_alt:string|null; tempo_leitura:string|null; tags:string[]|null; status?:"rascunho"|"publicado"|"arquivado"; destaque:boolean|null; views?:number|null; publicado_em:string|null; categoria:BlogDbCategory|null };
export type BlogAdminMetrics={totalViews:number;newsletterSubscribers:number;conversionRate:number;topPostWeek:{title:string;slug:string;views:number}|null;viewsLast7Days:{date:string;label:string;views:number}[]};
function createEmptyMetrics():BlogAdminMetrics{const formatter=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit"});const today=new Date();return{totalViews:0,newsletterSubscribers:0,conversionRate:0,topPostWeek:null,viewsLast7Days:Array.from({length:7},(_,index)=>{const date=new Date(today);date.setDate(today.getDate()-(6-index));const key=date.toISOString().slice(0,10);return{date:key,label:formatter.format(date),views:0};})};}
function splitBody(value:string){return value.split(/\n{2,}/).map(p=>p.trim()).filter(Boolean)}
function looksLikeHtml(value:string){return /<\/?[a-z][\s\S]*>/i.test(value)}
function looksLikeUuid(value?:string|null){return Boolean(String(value||"").match(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i))}
function readableCategoryName(category:BlogDbCategory){return looksLikeUuid(category.slug)||looksLikeUuid(category.nome.replace(/\s+/g,"-"))?"Agenda online":category.nome}
function mapCategory(category:BlogDbCategory):BlogCategory{return{id:category.id,slug:looksLikeUuid(category.slug)?"agenda-online":category.slug,name:readableCategoryName(category),description:category.descricao||"Artigos do blog SalãoPremium."}}
function mapPost(post:BlogDbPost):BlogPost{const category=post.categoria;return{id:post.id,slug:post.slug,title:post.titulo,description:post.descricao,excerpt:post.resumo||post.descricao,categorySlug:category?(looksLikeUuid(category.slug)?"agenda-online":category.slug):"gestao",categoryName:category?readableCategoryName(category):"Gestão",readTime:post.tempo_leitura||"5 min",publishedAt:post.publicado_em||new Date().toISOString(),coverImage:post.imagem_capa_url||"/marketing-kit/site-hero.png",coverAlt:post.imagem_capa_alt||post.titulo,tags:post.tags||[],body:splitBody(post.conteudo),bodyHtml:looksLikeHtml(post.conteudo)?post.conteudo:splitBody(post.conteudo).map(p=>`<p>${p}</p>`).join(""),featured:Boolean(post.destaque),views:Number(post.views||0),categoryId:post.categoria_id||category?.id,status:post.status||"publicado",rawContent:post.conteudo}}
function isSeoBlockedBlogPost(post:BlogDbPost){const slug=String(post.slug||"").toLowerCase();const title=String(post.titulo||"").toLowerCase();return slug.startsWith("post-teste-automatico")||slug.startsWith("teste-automatico")||title.includes("post teste automático")||title.includes("post teste automatico")}
async function getBlogDatabaseUnsafe():Promise<LooseDbClient|null>{if(!canUseBlogDatabase())return null;return asLooseDbClient(getBlogDatabase())}
