"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";
import { deleteClienteProfileAction, updateClienteProfileAction, type ClienteProfileState } from "@/app/app-cliente/perfil/actions";

function digits(value: string) { return value.replace(/\D/g, ""); }
function maskCpf(value: string) { const d = digits(value).slice(0,11); return d.replace(/^(\d{3})(\d)/,"$1.$2").replace(/^(\d{3})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1-$2"); }
function maskWhatsapp(value: string) { const d = digits(value).slice(0,11); if (d.length <= 2) return d ? `(${d}` : ""; if (d.length <= 6) return `(${d.slice(0,2)}) ${d.slice(2)}`; if (d.length <= 10) return `(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`; return `(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`; }
function SubmitButton() { const { pending } = useFormStatus(); return <button type="submit" disabled={pending} className="h-12 w-full rounded-2xl bg-zinc-950 text-sm font-black text-white disabled:opacity-60">{pending ? "Salvando..." : "Salvar alterações"}</button>; }

export default function ClientProfileForm({ nome, email, telefone, cpf, dataNascimento, preferenciasGerais, successKey }: { nome: string; email: string; telefone?: string | null; cpf?: string | null; dataNascimento?: string | null; preferenciasGerais?: string | null; successKey?: string | null }) {
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [state, formAction] = useActionState<ClienteProfileState, FormData>(updateClienteProfileAction, { error: null });
  const [cpfValue, setCpfValue] = useState(maskCpf(cpf || ""));
  const [phoneValue, setPhoneValue] = useState(maskWhatsapp(telefone || ""));
  return <div className="space-y-4">
    <form id="editar-cadastro" action={formAction} className="rounded-[1.5rem] border border-zinc-100 bg-white p-5 shadow-[0_14px_38px_rgba(15,23,42,0.06)]">
      <div className="text-[11px] font-black uppercase tracking-[0.16em] text-amber-700">Dados pessoais</div><h2 className="mt-1 text-xl font-black text-zinc-950">Editar perfil</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Mantenha CPF, nascimento e WhatsApp corretos para acesso e agendamentos.</p>
      <div className="mt-5 space-y-4">
        <div><label className="mb-1.5 block text-sm font-bold text-zinc-700">Nome completo</label><input name="nome" type="text" autoComplete="name" defaultValue={nome} required className="h-12 w-full rounded-xl border border-zinc-200 px-4 text-base outline-none focus:border-amber-400" /></div>
        <div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-bold text-zinc-700">CPF</label><input name="cpf" type="text" inputMode="numeric" value={cpfValue} onChange={(e)=>setCpfValue(maskCpf(e.target.value))} placeholder="000.000.000-00" maxLength={14} required className="h-12 w-full rounded-xl border border-zinc-200 px-4 text-base outline-none focus:border-amber-400" /></div><div><label className="mb-1.5 block text-sm font-bold text-zinc-700">Data de nascimento</label><input name="dataNascimento" type="date" autoComplete="bday" defaultValue={dataNascimento || ""} required className="h-12 w-full rounded-xl border border-zinc-200 px-4 text-base outline-none focus:border-amber-400" /></div></div>
        <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-900">Alterar CPF ou nascimento também atualiza os dados usados no seu acesso.</div>
        <div className="rounded-xl border border-zinc-200 bg-zinc-50 p-4"><div className="text-sm font-bold text-zinc-700">E-mail</div><div className="mt-1 break-all text-sm font-black text-zinc-950">{email || "Nenhum e-mail cadastrado"}</div><p className="mt-2 text-xs leading-5 text-zinc-500">A troca de e-mail exige verificação.</p><Link href="/app-cliente/recuperar-acesso" className="mt-3 inline-flex text-sm font-black text-amber-800 underline underline-offset-4">Alterar e-mail com verificação</Link></div>
        <div><label className="mb-1.5 block text-sm font-bold text-zinc-700">WhatsApp</label><input name="telefone" type="tel" autoComplete="tel" inputMode="tel" value={phoneValue} onChange={(e)=>setPhoneValue(maskWhatsapp(e.target.value))} maxLength={15} required className="h-12 w-full rounded-xl border border-zinc-200 px-4 text-base outline-none focus:border-amber-400" /></div>
        <div><label className="mb-1.5 block text-sm font-bold text-zinc-700">Preferências para atendimento</label><textarea name="preferencias" defaultValue={preferenciasGerais || ""} rows={4} placeholder="Ex.: profissional favorito, cuidados importantes ou preferências." className="w-full rounded-xl border border-zinc-200 px-4 py-3 text-base outline-none focus:border-amber-400" /></div>
        {successKey === "salvo" ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Perfil atualizado com sucesso.</div> : null}{successKey === "email_alterado" ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">E-mail atualizado e confirmado.</div> : null}{successKey === "erro_excluir" ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">Não foi possível encerrar sua conta agora.</div> : null}{state.error ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{state.error}</div> : null}<SubmitButton />
      </div>
    </form>
    <form action={deleteClienteProfileAction} className="rounded-[1.35rem] border border-red-100 bg-red-50 p-5"><h2 className="text-lg font-black text-red-900">Encerrar conta</h2><p className="mt-2 text-sm leading-6 text-red-800">Desativa seu acesso e cancela agendamentos futuros criados pelo App Cliente. O histórico operacional do salão permanece.</p>{confirmDelete ? <div className="mt-4 rounded-xl border border-red-200 bg-white p-3"><p className="text-sm font-black text-red-900">Confirmar encerramento?</p><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setConfirmDelete(false)} className="h-11 rounded-xl border border-zinc-200 bg-white px-3 text-sm font-bold">Manter conta</button><button type="submit" className="h-11 rounded-xl bg-red-700 px-3 text-sm font-bold text-white">Encerrar</button></div></div> : <button type="button" onClick={()=>setConfirmDelete(true)} className="mt-4 inline-flex h-11 items-center rounded-xl border border-red-200 bg-white px-4 text-sm font-black text-red-700">Excluir minha conta</button>}</form>
  </div>;
}
