import type { DatabaseClient } from "@/lib/db/types";
import { buildLoginRedirectUrl } from "@/lib/auth/login-redirect";
import type { PainelSessionSnapshot } from "@/lib/painel/session-snapshot";
import { PERMISSIONS, type PermissionKey, type UserNivel } from "@/lib/permissions";
import type { Cliente, ConfigSalao, Profissional, Servico } from "@/types/agenda";

type AuthUser = { id: string };
type ComboServicoAgendaRow = { id_servico_combo?: string | null; id_servico_item?: string | null; ativo?: boolean | null };

function montarPermissoesPorNivel(userNivel: UserNivel) { const keys = Object.keys(PERMISSIONS) as PermissionKey[]; return keys.reduce<Record<string, boolean>>((acc,key)=>{acc[key]=PERMISSIONS[key].includes(userNivel);return acc;},{}); }
function diferencaEmDias(dataAlvo: Date, dataBase: Date) { const alvo=new Date(dataAlvo.getFullYear(),dataAlvo.getMonth(),dataAlvo.getDate()); const base=new Date(dataBase.getFullYear(),dataBase.getMonth(),dataBase.getDate()); return Math.ceil((alvo.getTime()-base.getTime())/(1000*60*60*24)); }
function parseDataAssinatura(valor?: string|null){if(!valor)return null;const texto=String(valor).trim();if(!texto)return null;const dataCompleta=new Date(texto);if(!Number.isNaN(dataCompleta.getTime()))return dataCompleta;if(/^\d{4}-\d{2}-\d{2}$/.test(texto)){const d=new Date(`${texto}T23:59:59`);if(!Number.isNaN(d.getTime()))return d;}return null;}
function intersectProfessionalIds(serviceIds:string[],linksByService:Map<string,string[]>){if(serviceIds.length===0)return[];const[first,...others]=serviceIds;return(linksByService.get(first)||[]).filter(id=>others.every(s=>(linksByService.get(s)||[]).includes(id)));}
function getAssinaturaBloqueada(params:{status?:string|null;vencimentoEm?:string|null;trialFimEm?:string|null}){const s=String(params.status||"").toLowerCase();const base=["teste_gratis","trial"].includes(s)?(params.trialFimEm||params.vencimentoEm||null):(params.vencimentoEm||params.trialFimEm||null);if(!s||!base)return true;const v=parseDataAssinatura(base);if(!v)return true;const dias=diferencaEmDias(v,new Date());const vencida=dias<0;const atraso=vencida?Math.abs(dias):0;if(["teste_gratis","trial"].includes(s))return vencida;if(["ativo","ativa","pago","pendente","aguardando_pagamento"].includes(s))return vencida&&atraso>3;return true;}

export async function initAgendaPage(params:{supabase:DatabaseClient;safeGetAuthUser:()=>Promise<AuthUser|null>;sessionSnapshot?:PainelSessionSnapshot|null}):Promise<{ok:boolean;redirectTo?:string|null;erroTela?:string;permissoes?:Record<string,boolean>|null;idSalao?:string;config?:ConfigSalao|null;profissionais?:Profissional[];clientes?:Cliente[];servicos?:Servico[];assinaturaBloqueada?:boolean}>{
 const {supabase,safeGetAuthUser,sessionSnapshot}=params; let salaoId=sessionSnapshot?.idSalao||""; let userNivel=String(sessionSnapshot?.nivel||"recepcao") as UserNivel; let permissoesNivel=sessionSnapshot?.permissoes||montarPermissoesPorNivel(userNivel);
 if(!salaoId){const user=await safeGetAuthUser();if(!user)return{ok:false,redirectTo:buildLoginRedirectUrl("sessao_expirada",{returnTo:"/agenda",context:"agenda"}),erroTela:"Usuario nao autenticado."};const r=await supabase.from("usuarios").select("id, id_salao, status, auth_user_id, nivel").eq("auth_user_id",user.id).maybeSingle();if(r.error)return{ok:false,erroTela:"Nao foi possivel carregar os dados do usuario logado."};if(!r.data?.id_salao)return{ok:false,erroTela:"Nao foi possivel identificar o salao do usuario logado."};if(r.data.status&&r.data.status!=="ativo")return{ok:false,redirectTo:buildLoginRedirectUrl("usuario_inativo",{returnTo:"/agenda",context:"agenda"}),erroTela:"Usuario vinculado, mas inativo."};salaoId=r.data.id_salao;userNivel=String(r.data.nivel||"recepcao") as UserNivel;permissoesNivel=montarPermissoesPorNivel(userNivel);}
 if(!permissoesNivel.agenda_ver)return{ok:true,permissoes:permissoesNivel,redirectTo:"/dashboard"}; if(sessionSnapshot?.planoRecursos?.agenda===false)return{ok:true,permissoes:permissoesNivel,redirectTo:"/meu-plano?motivo=recurso_agenda_bloqueado"};
 const [configRes,profissionaisRes,clientesRes,servicosRes,vinculosServicosRes,comboItensRes,assinaturaRes]=await Promise.all([
 supabase.from("configuracoes_salao").select("*").eq("id_salao",salaoId).maybeSingle(),supabase.from("profissionais").select("*").eq("id_salao",salaoId).eq("status","ativo").or("tipo_profissional.is.null,tipo_profissional.eq.profissional").order("nome"),supabase.from("clientes").select("id, nome, whatsapp").eq("id_salao",salaoId).order("nome"),supabase.from("servicos").select("*").eq("id_salao",salaoId).eq("status","ativo").order("nome"),supabase.from("profissional_servicos").select("id_profissional, id_servico, ativo").eq("id_salao",salaoId).eq("ativo",true),supabase.from("servicos_combo_itens").select("id_servico_combo, id_servico_item, ativo").eq("id_salao",salaoId).eq("ativo",true),supabase.from("assinaturas").select("status, vencimento_em, trial_fim_em").eq("id_salao",salaoId).maybeSingle()]);
 const vinculos=new Map<string,string[]>();((vinculosServicosRes.data||[]) as {id_servico:string|null;id_profissional:string|null}[]).forEach(v=>{if(v.id_servico&&v.id_profissional)vinculos.set(v.id_servico,[...(vinculos.get(v.id_servico)||[]),v.id_profissional]);});const combos=new Map<string,string[]>();((comboItensRes.data||[]) as ComboServicoAgendaRow[]).forEach(i=>{if(i.id_servico_combo&&i.id_servico_item)combos.set(i.id_servico_combo,[...(combos.get(i.id_servico_combo)||[]),i.id_servico_item]);});const servicos=((servicosRes.data||[]) as Servico[]).map(s=>{const direct=vinculos.get(s.id)||[];const children=combos.get(s.id)||[];const derived=s.eh_combo&&children.length?intersectProfessionalIds(children,vinculos):[];return{...s,profissionais_vinculados:derived.length?derived:direct};});
 return{ok:true,permissoes:permissoesNivel,idSalao:salaoId,config:(configRes.data as ConfigSalao)||null,profissionais:(profissionaisRes.data as Profissional[])||[],clientes:(clientesRes.data as Cliente[])||[],servicos,assinaturaBloqueada:getAssinaturaBloqueada({status:assinaturaRes.data?.status,vencimentoEm:assinaturaRes.data?.vencimento_em||null,trialFimEm:assinaturaRes.data?.trial_fim_em||null}),erroTela:configRes.data?"":"Nao foi possivel carregar as configuracoes do salao."};
}
