import { redirect } from "next/navigation";
import { BookOpen, CalendarDays, FileSignature, GraduationCap, Users } from "lucide-react";
import { adicionarMaterial, atualizarContratoCurso, atualizarMatricula, criarCurso, criarTurma } from "@/app/cursos/actions";
import { resumoAdmin } from "@/lib/cursos/data";
import { emailPodeAdministrar, readCursoSession } from "@/lib/cursos/session";

export const dynamic="force-dynamic";
const d=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v));
export default async function AdminCursos({searchParams}:{searchParams:Promise<{erro?:string}>}){const session=await readCursoSession();if(!session||!(session.role==="admin"||session.role==="professor"||emailPodeAdministrar(session.email)))redirect("/admin-cursos/login");const [data,{erro}]=await Promise.all([resumoAdmin(),searchParams]);const cursos=data.cursos as any[];const turmas=data.turmas as any[];const matriculas=data.matriculas as any[];return <main className="cursos-main"><div className="cursos-wrap"><span className="cursos-eyebrow" style={{background:"#f2e8ef",color:"#6d235f"}}>Gestão acadêmica</span><h1 className="cursos-section-title" style={{marginTop:14}}>Administração de cursos</h1><p className="cursos-muted">Gerencie formações, turmas, materiais, presença e certificados.</p>{erro&&<p className="cursos-alert">{erro}</p>}<div className="cursos-stats" style={{marginTop:28}}><div className="cursos-stat"><BookOpen size={18}/> Cursos<strong>{cursos.length}</strong></div><div className="cursos-stat"><CalendarDays size={18}/> Turmas<strong>{turmas.length}</strong></div><div className="cursos-stat"><GraduationCap size={18}/> Matrículas<strong>{matriculas.length}</strong></div><div className="cursos-stat"><Users size={18}/> Alunos<strong>{data.totalAlunos}</strong></div></div>
 <section className="cursos-section" style={{paddingTop:28}}><h2>Alunas e conclusão</h2><div className="cursos-table-wrap"><table className="cursos-table"><thead><tr><th>Aluna</th><th>Curso / turma</th><th>Situação</th><th>Atualizar</th></tr></thead><tbody>{matriculas.map(m=><tr key={m.id}><td><strong>{m.aluno?.nome}</strong><br/>{m.aluno?.email}</td><td>{m.curso?.nome}<br/><span className="cursos-muted">{m.turma?.nome}</span></td><td>{m.status}<br/>{m.pagamento_status}<br/>{m.frequencia_percentual}% frequência</td><td><form action={atualizarMatricula} style={{display:"grid",gap:7,minWidth:190}}><input type="hidden" name="matricula_id" value={m.id}/><select name="status" defaultValue={m.status}><option value="pendente">Pendente</option><option value="confirmada">Confirmada</option><option value="em_andamento">Em andamento</option><option value="concluida">Concluída</option><option value="cancelada">Cancelada</option></select><select name="pagamento_status" defaultValue={m.pagamento_status}><option value="pendente">Pagamento pendente</option><option value="pago">Pago</option><option value="isento">Isento</option><option value="estornado">Estornado</option></select><input name="frequencia" type="number" min="0" max="100" defaultValue={m.frequencia_percentual} aria-label="Frequência"/><input name="progresso" type="number" min="0" max="100" defaultValue={m.progresso_percentual} aria-label="Progresso"/><button className="cursos-button" style={{minHeight:38,padding:8}}>Salvar</button></form></td></tr>)}</tbody></table></div></section>
 <div className="cursos-grid cursos-section"><form className="cursos-card" action={criarCurso}><h2>Novo curso</h2><div className="cursos-field"><label>Nome</label><input name="nome" required/></div><div className="cursos-field"><label>Slug</label><input name="slug" placeholder="curso-de-colorimetria" required/></div><div className="cursos-field"><label>Resumo</label><textarea name="resumo" required/></div><div className="cursos-field"><label>Descrição</label><textarea name="descricao" required/></div><div className="cursos-fields"><div className="cursos-field"><label>Carga horária</label><input name="carga_horaria" type="number" min="1" required/></div><div className="cursos-field"><label>Valor (R$)</label><input name="valor" type="number" min="0" step="0.01" required/></div></div><div className="cursos-field"><label>Versão do contrato</label><input name="contrato_versao" defaultValue="1.0" required/></div><div className="cursos-field"><label>Contrato completo</label><textarea name="contrato_conteudo" rows={12} placeholder="Digite aqui as cláusulas reais do contrato deste curso." required minLength={50}/></div><button className="cursos-button" style={{marginTop:16}}>Criar curso</button></form>
 <form className="cursos-card" action={criarTurma}><h2>Abrir turma</h2><div className="cursos-field"><label>Curso</label><select name="curso_id" required><option value="">Selecione</option>{cursos.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></div><div className="cursos-field"><label>Nome da turma</label><input name="nome" placeholder="Turma outubro 2026" required/></div><div className="cursos-field"><label>Início</label><input name="inicio_em" type="datetime-local" required/></div><div className="cursos-field"><label>Fim</label><input name="fim_em" type="datetime-local" required/></div><div className="cursos-field"><label>Local</label><input name="local" required/></div><div className="cursos-field"><label>Vagas</label><input name="vagas" type="number" min="1" required/></div><button className="cursos-button" style={{marginTop:16}}>Abrir turma</button></form>
 <form className="cursos-card" action={adicionarMaterial}><h2>Publicar material</h2><div className="cursos-field"><label>Curso</label><select name="curso_id" required><option value="">Selecione</option>{cursos.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></div><div className="cursos-field"><label>Novo módulo</label><input name="modulo" placeholder="Fundamentos" required/></div><div className="cursos-field"><label>Ordem</label><input name="ordem" type="number" min="1" defaultValue="1"/></div><div className="cursos-field"><label>Título do material</label><input name="titulo" required/></div><div className="cursos-field"><label>PDF, imagem ou vídeo (máx. 25 MB)</label><input name="arquivo" type="file" accept="application/pdf,image/jpeg,image/png,video/mp4"/></div><div className="cursos-field"><label>Ou URL de vídeo</label><input name="url" type="url"/></div><button className="cursos-button" style={{marginTop:16}}>Publicar material</button></form></div>
 <section className="cursos-section"><h2><FileSignature size={20} style={{verticalAlign:"middle"}}/> Contratos dos cursos</h2><p className="cursos-muted">O texto salvo aqui é o texto real mostrado à aluna e preservado como cópia na assinatura.</p><div className="cursos-grid">{cursos.length?cursos.map(c=><form className="cursos-card" action={atualizarContratoCurso} key={c.id}><input type="hidden" name="curso_id" value={c.id}/><h3>{c.nome}</h3><div className="cursos-field"><label>Versão</label><input name="contrato_versao" defaultValue={c.contrato_versao||"1.0"} required/></div><div className="cursos-field"><label>Texto completo do contrato</label><textarea name="contrato_conteudo" rows={14} defaultValue={c.contrato_conteudo||""} required minLength={50}/></div><button className="cursos-button">Salvar contrato</button></form>):<div className="cursos-card"><p className="cursos-muted">Crie seu primeiro curso real para configurar o contrato.</p></div>}</div></section>
 <section className="cursos-section"><h2>Turmas cadastradas</h2><div className="cursos-table-wrap"><table className="cursos-table"><thead><tr><th>Curso</th><th>Turma</th><th>Data</th><th>Local</th><th>Vagas</th></tr></thead><tbody>{turmas.map(t=><tr key={t.id}><td>{t.curso?.nome}</td><td>{t.nome}</td><td>{d(t.inicio_em)}</td><td>{t.local}</td><td>{t.vagas}</td></tr>)}</tbody></table></div></section>
 </div></main>}
