create table if not exists public.whatsapp_support_conversations (
  id uuid primary key default gen_random_uuid(),
  wa_id text not null unique,
  telefone text not null,
  nome_contato text,
  status text not null default 'aberta' check (status in ('aberta','pendente','encerrada')),
  nao_lidas integer not null default 0 check (nao_lidas >= 0),
  ultima_mensagem_em timestamptz not null default now(),
  ultima_mensagem_preview text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.whatsapp_support_messages (
  id bigint generated by default as identity primary key,
  conversa_id uuid not null references public.whatsapp_support_conversations(id) on delete cascade,
  wamid text unique,
  direcao text not null check (direcao in ('entrada','saida')),
  tipo text not null default 'text',
  conteudo text,
  status text not null default 'recebida',
  criado_em timestamptz not null default now()
);

create index if not exists whatsapp_support_conversations_lista_idx
  on public.whatsapp_support_conversations (status, ultima_mensagem_em desc);
create index if not exists whatsapp_support_messages_conversa_idx
  on public.whatsapp_support_messages (conversa_id, criado_em desc);

alter table public.whatsapp_support_conversations enable row level security;
alter table public.whatsapp_support_messages enable row level security;
revoke all on public.whatsapp_support_conversations from anon, authenticated;
revoke all on public.whatsapp_support_messages from anon, authenticated;
grant all on public.whatsapp_support_conversations to service_role;
grant all on public.whatsapp_support_messages to service_role;
grant usage, select on sequence public.whatsapp_support_messages_id_seq to service_role;

create or replace function public.ingest_whatsapp_support_message(
  p_wa_id text,
  p_telefone text,
  p_nome_contato text,
  p_wamid text,
  p_tipo text,
  p_conteudo text,
  p_criado_em timestamptz default now()
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conversa_id uuid;
  v_msg_id bigint;
begin
  insert into public.whatsapp_support_conversations (
    wa_id, telefone, nome_contato, ultima_mensagem_em, ultima_mensagem_preview
  ) values (
    left(p_wa_id, 32), left(p_telefone, 32), nullif(left(coalesce(p_nome_contato, ''), 160), ''),
    p_criado_em, left(coalesce(p_conteudo, '[' || coalesce(p_tipo, 'mensagem') || ']'), 240)
  )
  on conflict (wa_id) do update set
    telefone = excluded.telefone,
    nome_contato = coalesce(excluded.nome_contato, whatsapp_support_conversations.nome_contato),
    atualizado_em = now()
  returning id into v_conversa_id;

  insert into public.whatsapp_support_messages (
    conversa_id, wamid, direcao, tipo, conteudo, status, criado_em
  ) values (
    v_conversa_id, nullif(left(coalesce(p_wamid, ''), 255), ''), 'entrada',
    left(coalesce(p_tipo, 'text'), 32), left(p_conteudo, 4096), 'recebida', p_criado_em
  )
  on conflict (wamid) do nothing
  returning id into v_msg_id;

  if v_msg_id is not null then
    update public.whatsapp_support_conversations
    set nao_lidas = nao_lidas + 1,
        ultima_mensagem_em = p_criado_em,
        ultima_mensagem_preview = left(coalesce(p_conteudo, '[' || coalesce(p_tipo, 'mensagem') || ']'), 240),
        atualizado_em = now(),
        status = case when status = 'encerrada' then 'aberta' else status end
    where id = v_conversa_id;
  end if;

  return v_conversa_id;
end;
$$;

revoke all on function public.ingest_whatsapp_support_message(text,text,text,text,text,text,timestamptz) from public, anon, authenticated;
grant execute on function public.ingest_whatsapp_support_message(text,text,text,text,text,text,timestamptz) to service_role;
