name: salao_premium_profissional
description: Aplicativo profissional Salão Premium, 100% Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/brand-logo.png
