import { Clock, HelpCircle, KeyRound, Mail, Phone, ShieldCheck, Smartphone, UserRound, WalletCards } from "lucide-react";
import { FormEvent, useState } from "react";
import { Button } from "../components/ui/Button";
import { Field, Input } from "../components/ui/Input";
import { Modal, ModalActionBar } from "../components/ui/Modal";
import type { Profissional } from "../types/database";

function formatCpf(value?: string | null) { const d=String(value||"").replace(/\D/g,"").slice(0,11); return d.length===11 ? d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,"$1.$2.$3-$4") : value || "Não informado"; }
function formatPhone(value?: string | null) { const d=String(value||"").replace(/\D/g,""); if(d.length===11)return d.replace(/(\d{2})(\d{5})(\d{4})/,"($1) $2-$3"); if(d.length===10)return d.replace(/(\d{2})(\d{4})(\d{4})/,"($1) $2-$3"); return value || "Não informado"; }

export function PerfilPage({ profissional, goTo }: { profissional: Profissional; goTo: (view: "configuracoes" | "suporte" | "duvidas" | "instalar" | "privacidade") => void; }) {
  const [passwordOpen,setPasswordOpen]=useState(false); const nome=profissional.nome_exibicao||profissional.nome;
  return <div className="space-y-4 pb-6">
    <section className="rounded-[1.4rem] border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-[1.15rem] bg-amber-50 text-amber-800"><UserRound size={30}/></div><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-700">Meu perfil</p><h2 className="mt-1 truncate text-2xl font-black tracking-[-.05em] text-zinc-950">{nome}</h2><p className="text-sm font-bold text-zinc-500">{profissional.cargo||profissional.categoria||"Profissional"}</p></div></div></section>
    <section className="rounded-[1.4rem] border border-zinc-200 bg-white p-4 shadow-sm"><div className="mb-3"><h3 className="text-xl font-black tracking-[-.04em]">Informações</h3><p className="text-sm font-semibold text-zinc-500">Seus dados profissionais e de recebimento</p></div><div className="divide-y divide-zinc-100"><Info icon={<Phone size={19}/>} label="Telefone / WhatsApp" value={formatPhone(profissional.whatsapp||profissional.telefone)}/><Info icon={<Mail size={19}/>} label="E-mail" value={profissional.email||"Não informado"}/><Info icon={<ShieldCheck size={19}/>} label="CPF" value={formatCpf(profissional.cpf)}/><Info icon={<WalletCards size={19}/>} label={`Pix${profissional.pix_tipo ? ` · ${profissional.pix_tipo}`:""}`} value={profissional.pix_chave||profissional.sinal_pix_recebedor||"Não informado"}/><Info icon={<Clock size={19}/>} label="Intervalo da agenda" value={`${profissional.intervalo_agenda_minutos||30} minutos`}/></div></section>
    <button onClick={()=>goTo("configuracoes")} className="flex w-full items-center gap-3 rounded-[1.25rem] border border-amber-200 bg-amber-50/60 p-4 text-left"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-amber-800"><Clock size={21}/></div><div><div className="font-black">Editar perfil e horários</div><div className="text-sm font-semibold text-zinc-500">Dados, expediente e intervalo da agenda</div></div></button>
    <div className="grid gap-2"><ProfileAction icon={<KeyRound size={20}/>} title="Trocar senha" text="Segurança do seu acesso" onClick={()=>setPasswordOpen(true)}/><ProfileAction icon={<Smartphone size={20}/>} title="Instalar app" text="Adicionar à tela inicial" onClick={()=>goTo("instalar")}/><ProfileAction icon={<HelpCircle size={20}/>} title="Suporte e dúvidas" text="Ajuda para usar o aplicativo" onClick={()=>goTo("suporte")}/><ProfileAction icon={<ShieldCheck size={20}/>} title="Privacidade" text="Termos e regras de uso" onClick={()=>goTo("privacidade")}/></div>
    <Modal title="Trocar senha" subtitle="Crie uma nova senha para o App Profissional." open={passwordOpen} onClose={()=>setPasswordOpen(false)}><PasswordForm/></Modal>
  </div>;
}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center gap-3 py-3 first:pt-1 last:pb-1"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-zinc-50 text-zinc-500">{icon}</div><div className="min-w-0"><div className="text-[11px] font-black uppercase tracking-[.16em] text-zinc-400">{label}</div><div className="mt-0.5 break-words text-sm font-black text-zinc-900">{value}</div></div></div>}
function PasswordForm(){const[senhaAtual,setSenhaAtual]=useState("");const[senha,setSenha]=useState("");const[confirmar,setConfirmar]=useState("");const[erro,setErro]=useState("");const[loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setErro("");if(!senhaAtual)return setErro("Informe sua senha atual.");if(senha.length<6)return setErro("A nova senha precisa ter pelo menos 6 caracteres.");if(senhaAtual===senha)return setErro("Escolha uma senha diferente da atual.");if(senha!==confirmar)return setErro("As senhas não conferem.");setLoading(true);try{const r=await fetch("/api/app-profissional/mutacoes",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"trocar_senha",senhaAtual,senha})});const p=await r.json().catch(()=>({}));if(!r.ok||!p.ok)throw new Error(String(p.error||"Não foi possível trocar a senha."));window.location.assign("/app-profissional/")}catch(error){setErro(error instanceof Error?error.message:"Não foi possível trocar a senha.");setLoading(false)}}return <form onSubmit={submit} className="grid gap-3"><Field label="Senha atual"><Input type="password" value={senhaAtual} onChange={e=>setSenhaAtual(e.target.value)}/></Field><Field label="Nova senha"><Input type="password" value={senha} onChange={e=>setSenha(e.target.value)}/></Field><Field label="Confirmar nova senha"><Input type="password" value={confirmar} onChange={e=>setConfirmar(e.target.value)}/></Field>{erro?<div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{erro}</div>:null}<ModalActionBar><Button loading={loading}>Salvar nova senha</Button></ModalActionBar></form>}
function ProfileAction({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className="flex items-center gap-3 rounded-[1.1rem] border border-zinc-200 bg-white p-3.5 text-left"><div className="grid h-10 w-10 place-items-center rounded-xl bg-zinc-50">{icon}</div><div><div className="font-black">{title}</div><div className="text-sm font-semibold text-zinc-500">{text}</div></div></button>}
